apiVersion: v1
kind: Service
metadata:
  name: kbset343ffsw
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "kbset343ffsw"
    port: 8080
  selector:
    app: kbset343ffsw
